cities: [bogor, warsaw]

per_city:
  bogor:
    base_dir: /content/drive/MyDrive/crash-dualgraph/data
    boundary_geojson: ${base_dir}/boundary/study-area.geojson
    positive_front_view_dir: ${base_dir}/positive/front-view
    positive_metadata_csv: ${base_dir}/positive/panorama/metadata_outofrange_removed.csv
    positive_points_csv: ${base_dir}/positive/points/positive_points.csv
    negative_front_view_dir: ${base_dir}/negative/front-view
    negative_metadata_csv: ${base_dir}/negative/panorama/metadata_outofrange_removed.csv
    negative_points_csv: ${base_dir}/negative/points/negative_points.csv
    interim_dir: ${base_dir}/interim
    processed_dir: ${base_dir}/processed
    outputs_dir: ${base_dir}/outputs
  warsaw:
    base_dir: /content/drive/MyDrive/crash-dualgraph/data/warsaw
    boundary_geojson: /content/drive/MyDrive/crash-dualgraph/data/boundary/warsaw_boundary.geojson
    positive_front_view_dir: ${base_dir}/positive/front-view
    positive_metadata_csv: ${base_dir}/positive/panorama/metadata_outofrange_removed.csv
    positive_points_csv: ${base_dir}/positive/points/positive_points.csv
    negative_front_view_dir: ${base_dir}/negative/front-view
    negative_metadata_csv: ${base_dir}/negative/panorama/metadata_outofrange_removed.csv
    negative_points_csv: ${base_dir}/negative/points/negative_points.csv
    interim_dir: ${base_dir}/interim
    processed_dir: ${base_dir}/processed
    outputs_dir: ${base_dir}/outputs

combined:
  outputs_dir: /content/drive/MyDrive/crash-dualgraph/data/combined/outputs

random_seed: 42
approx_n_positive: 1100
approx_n_negative: 1100
