base_dir: /content/drive/MyDrive/crash-dualgraph/data
boundary_geojson: /content/drive/MyDrive/crash-dualgraph/data/boundary/study-area.geojson
positive_front_view_dir: /content/drive/MyDrive/crash-dualgraph/data/positive/front-view
positive_metadata_csv: /content/drive/MyDrive/crash-dualgraph/data/positive/panorama/metadata_outofrange_removed.csv
positive_points_csv: /content/drive/MyDrive/crash-dualgraph/data/positive/points/positive_points.csv
negative_front_view_dir: /content/drive/MyDrive/crash-dualgraph/data/negative/front-view
negative_metadata_csv: /content/drive/MyDrive/crash-dualgraph/data/negative/panorama/metadata_outofrange_removed.csv
negative_points_csv: /content/drive/MyDrive/crash-dualgraph/data/negative/points/negative_points.csv
interim_dir: /content/drive/MyDrive/crash-dualgraph/data/interim
processed_dir: /content/drive/MyDrive/crash-dualgraph/data/processed
outputs_dir: /content/drive/MyDrive/crash-dualgraph/data/outputs
random_seed: 42
approx_n_positive: 460
approx_n_negative: 460
